#!/bin/bash

# Supabase Dashboard Configuration Checker
echo "🔧 Supabase Dashboard Configuration Checklist"
echo "=============================================="
echo ""
echo "📋 Complete these steps in your Supabase Dashboard:"
echo ""
echo "1️⃣ Authentication → Providers → Google:"
echo "   ✓ Enable Google provider"
echo "   ✓ Client ID: 631111437135-iuippmjn73ur1g4thacjmr5lq3k315t0.apps.googleusercontent.com"
echo "   ✓ Client Secret: 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"
echo ""
echo "2️⃣ Authentication → URL Configuration:"
echo "   ✓ Site URL: http://localhost:3000"
echo "   ✓ Redirect URLs:"
echo "     - http://localhost:3000"
echo "     - http://localhost:8080"
echo "     - http://127.0.0.1:3000" 
echo "     - http://127.0.0.1:8080"
echo "     - https://xxasezacvotitccxnpaa.supabase.co/auth/v1/callback"
echo "     - com.moodtracker.app://auth"
echo ""
echo "3️⃣ Google Cloud Console Configuration:"
echo "   🌐 Web OAuth Client (631111437135-iuippmjn73ur1g4thacjmr5lq3k315t0):"
echo "   ✓ Authorized JavaScript origins:"
echo "     - http://localhost:3000"
echo "     - http://localhost:8080"
echo "     - http://127.0.0.1:3000"
echo "     - http://127.0.0.1:8080"
echo "     - https://xxasezacvotitccxnpaa.supabase.co"
echo ""
echo "   ✓ Authorized redirect URIs:"
echo "     - https://xxasezacvotitccxnpaa.supabase.co/auth/v1/callback"
echo "     - http://localhost:3000"
echo "     - http://localhost:8080"
echo "     - http://127.0.0.1:3000"
echo "     - http://127.0.0.1:8080"
echo ""
echo "📱 Mobile OAuth Clients:"
echo "   🤖 Android: 631111437135-76ojbi40r925em3sinj9igoel5f4do1i.apps.googleusercontent.com"
echo "   🍎 iOS: 631111437135-5iajfi8mlc0olt9bla8tqhic6sior22j.apps.googleusercontent.com"
echo ""
echo "🧪 Test the setup:"
echo "1. Go to http://localhost:3000"
echo "2. Click 'Sign in with Google'"
echo "3. Should redirect to Google OAuth"
echo "4. After consent, should return authenticated"
echo ""
echo "❗ If OAuth fails, check:"
echo "• Supabase redirect URLs match exactly"
echo "• Google Console origins/redirects are correct"
echo "• Client IDs match between Supabase and Google Console"
echo "• No typos in configuration"

# Test if Supabase is reachable
echo ""
echo "🌐 Testing Supabase connectivity..."
if curl -s "https://xxasezacvotitccxnpaa.supabase.co/rest/v1/" > /dev/null; then
    echo "✅ Supabase instance is reachable"
else
    echo "❌ Supabase instance not reachable"
fi

echo ""
echo "🔗 Useful Links:"
echo "• Supabase Dashboard: https://supabase.com/dashboard/project/xxasezacvotitccxnpaa"
echo "• Google Cloud Console: https://console.cloud.google.com/apis/credentials"
echo "• OAuth Testing: http://localhost:3000"
