#!/bin/bash

# Google OAuth Redirect URI Fix Script
echo "🔧 Fixing Google OAuth Redirect URI Issue"
echo ""

echo "📋 Current Configuration:"
echo "   Web Client ID: 631111437135-l2a14dgadurrj360mbom28saane8fngu.apps.googleusercontent.com"
echo "   Error Port: localhost:50070"
echo ""

echo "🌐 Step 1: Update Google Cloud Console"
echo ""
echo "1. Go to: https://console.cloud.google.com/"
echo "2. Navigate to: APIs & Services → Credentials"
echo "3. Find your OAuth 2.0 Client ID: 631111437135-l2a14dgadurrj360mbom28saane8fngu.apps.googleusercontent.com"
echo "4. Click Edit (pencil icon)"
echo ""

echo "📍 Step 2: Add Authorized JavaScript Origins"
echo ""
echo "Add these origins to your Google Cloud Console:"
echo "   ✓ http://localhost:3000"
echo "   ✓ http://localhost:8080" 
echo "   ✓ http://localhost:50070"
echo "   ✓ http://127.0.0.1:3000"
echo "   ✓ http://127.0.0.1:8080"
echo "   ✓ http://127.0.0.1:50070"
echo "   ✓ https://xxasezacvotitccxnpaa.supabase.co"
echo ""

echo "🔄 Step 3: Add Authorized Redirect URIs"
echo ""
echo "Add these redirect URIs to your Google Cloud Console:"
echo "   ✓ http://localhost:3000/auth/callback"
echo "   ✓ http://localhost:8080/auth/callback"
echo "   ✓ http://localhost:50070/auth/callback"
echo "   ✓ http://127.0.0.1:3000/auth/callback"
echo "   ✓ http://127.0.0.1:8080/auth/callback"
echo "   ✓ http://127.0.0.1:50070/auth/callback"
echo "   ✓ https://xxasezacvotitccxnpaa.supabase.co/auth/v1/callback"
echo ""

echo "💾 Step 4: Save and Wait"
echo "   - Click 'Save' in Google Cloud Console"
echo "   - Wait 2-3 minutes for changes to propagate"
echo ""

echo "🧪 Step 5: Test Commands"
echo ""
echo "After updating Google Cloud Console, run one of these:"
echo ""
echo "   # Test with port 3000 (recommended)"
echo "   flutter run -d chrome --web-port=3000"
echo ""
echo "   # Test with port 8080"
echo "   flutter run -d chrome --web-port=8080"
echo ""
echo "   # Test with original port 50070"
echo "   flutter run -d chrome --web-port=50070"
echo ""

echo "📱 Step 6: Update Supabase (if needed)"
echo ""
echo "1. Go to: https://supabase.com/dashboard"
echo "2. Select your project"
echo "3. Navigate to: Authentication → Providers → Google"
echo "4. Verify Client ID: 631111437135-l2a14dgadurrj360mbom28saane8fngu.apps.googleusercontent.com"
echo "5. Add redirect URLs if missing"
echo ""

echo "⚠️  Important Notes:"
echo "   - Both JavaScript origins AND redirect URIs must be added"
echo "   - The port in the error (50070) must exactly match Google Cloud Console"
echo "   - Changes may take a few minutes to take effect"
echo "   - Clear browser cache if issues persist"
echo ""

echo "✅ After completing these steps, Google Sign-In should work!"
