#!/bin/bash

echo "🧪 Testing Google Authentication - Updated Setup"
echo "================================================"
echo ""

# Test current Flutter app
echo "🌐 Current Flutter App Status:"
if curl -s http://localhost:3001 > /dev/null; then
    echo "✅ Flutter app running on http://localhost:3001"
else
    echo "❌ Flutter app not running on localhost:3001"
fi

echo ""
echo "🔧 Required Supabase Dashboard Configuration:"
echo "1. Go to: https://supabase.com/dashboard/project/xxasezacvotitccxnpaa"
echo "2. Navigate to: Authentication → Providers → Google"
echo "3. Enable Google provider and add:"
echo "   - Client ID: 631111437135-iuippmjn73ur1g4thacjmr5lq3k315t0.apps.googleusercontent.com"
echo "   - Client Secret: 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"
echo ""
echo "4. Navigate to: Authentication → URL Configuration"
echo "5. Add these redirect URLs:"
echo "   - http://localhost:3001"
echo "   - http://localhost:3000"
echo "   - http://localhost:8080"
echo "   - http://127.0.0.1:3001"
echo "   - http://127.0.0.1:3000"
echo "   - https://xxasezacvotitccxnpaa.supabase.co/auth/v1/callback"
echo ""
echo "🔧 Required Google Cloud Console Configuration:"
echo "1. Go to: https://console.cloud.google.com/apis/credentials"
echo "2. Find your OAuth 2.0 Client (Web): 631111437135-iuippmjn73ur1g4thacjmr5lq3k315t0"
echo "3. Add these Authorized JavaScript origins:"
echo "   - http://localhost:3001"
echo "   - http://localhost:3000"
echo "   - http://localhost:8080"
echo "   - http://127.0.0.1:3001"
echo "   - http://127.0.0.1:3000"
echo "   - https://xxasezacvotitccxnpaa.supabase.co"
echo ""
echo "4. Add these Authorized redirect URIs:"
echo "   - https://xxasezacvotitccxnpaa.supabase.co/auth/v1/callback"
echo "   - http://localhost:3001"
echo "   - http://localhost:3000"
echo ""
echo "🧪 How to Test:"
echo "1. Complete the configuration above"
echo "2. Open: http://localhost:3001"
echo "3. Click 'Sign in with Google'"
echo "4. Should redirect to Google OAuth consent screen"
echo "5. Grant permissions and return to app"
echo "6. Should be signed in successfully"
echo ""
echo "🚨 Common Issues & Solutions:"
echo "• 'Invalid redirect_uri': Add all localhost URLs to Google Console"
echo "• 'Unauthorized domain': Add origins to Google Console"
echo "• 'Configuration error': Check client ID/secret in Supabase"
echo "• Popup blocked: Allow popups for localhost"
echo ""
echo "📱 For Mobile Testing:"
echo "• Android: Check SHA-1 fingerprint registration"
echo "• iOS: Verify iOS client ID in app configuration"
echo ""
echo "🔗 Direct Links:"
echo "• Test App: http://localhost:3001"
echo "• Supabase: https://supabase.com/dashboard/project/xxasezacvotitccxnpaa"
echo "• Google Console: https://console.cloud.google.com/apis/credentials"
