// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZRTuA_2X_GUvAShWj8fm1RbA1h_ga9pc',
    appId: '1:339369629725:web:354a44ac5401c505754ef4',
    messagingSenderId: '339369629725',
    projectId: 'moodtracker-75a2f',
    authDomain: 'moodtracker-75a2f.firebaseapp.com',
    storageBucket: 'moodtracker-75a2f.firebasestorage.app',
    measurementId: 'G-BBWCLKK464',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE4_2s3qoU6pp29KIcj9i4AdRRsW8NPJk',
    appId: '1:339369629725:android:8419efd2b485d0d1754ef4',
    messagingSenderId: '339369629725',
    projectId: 'moodtracker-75a2f',
    storageBucket: 'moodtracker-75a2f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkOZ_jLvdi6weIF9OlbIM-q7_L1AlUKog',
    appId: '1:339369629725:ios:26b098deecc4fff9754ef4',
    messagingSenderId: '339369629725',
    projectId: 'moodtracker-75a2f',
    storageBucket: 'moodtracker-75a2f.firebasestorage.app',
    androidClientId: '339369629725-jp65m3gghjq44jortj9on2m66hr52o1v.apps.googleusercontent.com',
    iosClientId: '339369629725-lekp3l12v8385i36lhgvviotrri585mt.apps.googleusercontent.com',
    iosBundleId: 'com.example.moodTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkOZ_jLvdi6weIF9OlbIM-q7_L1AlUKog',
    appId: '1:339369629725:ios:26b098deecc4fff9754ef4',
    messagingSenderId: '339369629725',
    projectId: 'moodtracker-75a2f',
    storageBucket: 'moodtracker-75a2f.firebasestorage.app',
    androidClientId: '339369629725-jp65m3gghjq44jortj9on2m66hr52o1v.apps.googleusercontent.com',
    iosClientId: '339369629725-lekp3l12v8385i36lhgvviotrri585mt.apps.googleusercontent.com',
    iosBundleId: 'com.example.moodTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZRTuA_2X_GUvAShWj8fm1RbA1h_ga9pc',
    appId: '1:339369629725:web:87b909a1a3f2c5bc754ef4',
    messagingSenderId: '339369629725',
    projectId: 'moodtracker-75a2f',
    authDomain: 'moodtracker-75a2f.firebaseapp.com',
    storageBucket: 'moodtracker-75a2f.firebasestorage.app',
    measurementId: 'G-ZMWCQNQ8KJ',
  );
}
